language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install python-wxtools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests --with-coverage
after_success:
  - coveralls

notifications:
  email: false
